# -*- coding: utf-8 -*-

DEFAULT_LANGUAGE = 'en'
SUPPORTED_LANGUAGES = (
  'be', 'bg', 'cs', 'da', 'de', 'el', 'en', 'es', 'fi', 'fr', 'hr',
  'hu', 'it', 'lt', 'lv', 'nl', 'no', 'pl', 'pt', 'ro', 'ru', 'sr',
  'sv', 'tr', 'uk',
)

_KEYS = (
  'modName', 'modDescription', 'title',
  'showMaskPoints', 'showSpotPoints', 'showUiPoints', 'showGuides',
  'showTooltips',
  'group3d', 'groupUi', 'callouts',
  'calloutOff', 'calloutA', 'calloutB',
  'allowTurretRotation', 'layoutDebug',
  'rear', 'front', 'left', 'right', 'gunStatic', 'top', 'gunMoving',
)

# The target locale list comes from the wot-eu and mt-ru client snapshots.
# Point names follow official game terminology where it is published.  For
# locales without an attested game term, the closest semantic translation is
# used.  Named entries keep longer translations readable and easy to audit.
_TRANSLATIONS = {
  'be': {
    'modName': u"Габарытныя кропкі",
    'modDescription': u"Налады габарытных і аглядных кропак",
    'title': u"Габарытныя і аглядныя кропкі",
    'showMaskPoints': u"Габарытныя кропкі",
    'showSpotPoints': u"Аглядныя кропкі",
    'showUiPoints': u"Паказваць маркеры",
    'showGuides': u"Накіравальныя",
    'showTooltips': u"Паказваць падказкі",
    'group3d': u"3D",
    'groupUi': u"UI",
    'callouts': u"Подпісы",
    'calloutOff': u"Не паказваць",
    'calloutA': u"Варыянт А",
    'calloutB': u"Варыянт Б",
    'allowTurretRotation': u"Дазволіць варочаць вежу мышшу",
    'layoutDebug': u"Адладачная адмалёўка зон размяшчэння",
    'rear': u"Задняя габарытная",
    'front': u"Пярэдняя габарытная",
    'left': u"Левая бартавая габарытная",
    'right': u"Правая бартавая габарытная",
    'gunStatic': u"Пачатковая гарматная габарытная",
    'top': u"Верхняя аглядна-габарытная",
    'gunMoving': u"Гарматная аглядна-габарытная",
  },
  'bg': {
    'modName': u"Контролни точки на видимостта",
    'modDescription': u"Настройки на контролните точки на видимостта и обзорните точки",
    'title': u"Контролни точки на видимостта и обзорни точки",
    'showMaskPoints': u"Контролни точки на видимостта",
    'showSpotPoints': u"Обзорни точки",
    'showUiPoints': u"Показване на маркерите",
    'showGuides': u"Водачи",
    'showTooltips': u"Показване на подсказки",
    'group3d': u"3D",
    'groupUi': u"UI",
    'callouts': u"Етикети",
    'calloutOff': u"Без показване",
    'calloutA': u"Вариант A",
    'calloutB': u"Вариант B",
    'allowTurretRotation': u"Разрешаване на въртенето на кулата с мишката",
    'layoutDebug': u"Отладъчно изчертаване на зоните за разполагане",
    'rear': u"Задна контролна точка на видимостта",
    'front': u"Предна контролна точка на видимостта",
    'left': u"Лява странична контролна точка на видимостта",
    'right': u"Дясна странична контролна точка на видимостта",
    'gunStatic': u"Изходна контролна точка на видимостта при оръдието",
    'top': u"Горна контролна точка на видимостта / обзорна точка",
    'gunMoving': u"Контролна точка на видимостта при оръдието / обзорна точка",
  },
  'cs': {
    'modName': u"Body viditelnosti",
    'modDescription': u"Nastavení bodů viditelnosti a portů dohledu",
    'title': u"Body viditelnosti a porty dohledu",
    'showMaskPoints': u"Body viditelnosti",
    'showSpotPoints': u"Porty dohledu",
    'showUiPoints': u"Zobrazit značky",
    'showGuides': u"Vodicí čáry",
    'showTooltips': u"Zobrazit nápovědy",
    'group3d': u"3D",
    'groupUi': u"UI",
    'callouts': u"Popisky",
    'calloutOff': u"Nezobrazovat",
    'calloutA': u"Varianta A",
    'calloutB': u"Varianta B",
    'allowTurretRotation': u"Povolit otáčení věže myší",
    'layoutDebug': u"Ladicí vykreslení zón umístění",
    'rear': u"Zadní bod viditelnosti",
    'front': u"Přední bod viditelnosti",
    'left': u"Levý boční bod viditelnosti",
    'right': u"Pravý boční bod viditelnosti",
    'gunStatic': u"Výchozí bod viditelnosti děla",
    'top': u"Horní bod viditelnosti / port dohledu",
    'gunMoving': u"Bod viditelnosti děla / port dohledu",
  },
  'da': {
    'modName': u"Synlighedskontrolpunkter",
    'modDescription': u"Indstillinger for synlighedskontrol- og observationspunkter",
    'title': u"Synlighedskontrol- og observationspunkter",
    'showMaskPoints': u"Synlighedskontrolpunkter",
    'showSpotPoints': u"Observationspunkter",
    'showUiPoints': u"Vis markører",
    'showGuides': u"Hjælpelinjer",
    'showTooltips': u"Vis værktøjstip",
    'group3d': u"3D",
    'groupUi': u"UI",
    'callouts': u"Etiketter",
    'calloutOff': u"Vis ikke",
    'calloutA': u"Variant A",
    'calloutB': u"Variant B",
    'allowTurretRotation': u"Tillad tårnrotation med musen",
    'layoutDebug': u"Fejlfindingsvisning af placeringszoner",
    'rear': u"Bageste synlighedskontrolpunkt",
    'front': u"Forreste synlighedskontrolpunkt",
    'left': u"Venstre synlighedskontrolpunkt",
    'right': u"Højre synlighedskontrolpunkt",
    'gunStatic': u"Fast synlighedskontrolpunkt ved kanonen",
    'top': u"Øverste synlighedskontrolpunkt / observationspunkt",
    'gunMoving': u"Kanonens synlighedskontrolpunkt / observationspunkt",
  },
  'de': {
    'modName': u"Sichtbarkeitspunkte",
    'modDescription': u"Einstellungen für Sichtbarkeitspunkte und Sichtfenster",
    'title': u"Sichtbarkeitspunkte und Sichtfenster",
    'showMaskPoints': u"Sichtbarkeitspunkte",
    'showSpotPoints': u"Sichtfenster",
    'showUiPoints': u"Markierungen anzeigen",
    'showGuides': u"Hilfslinien",
    'showTooltips': u"Tooltips anzeigen",
    'group3d': u"3D",
    'groupUi': u"UI",
    'callouts': u"Beschriftungen",
    'calloutOff': u"Nicht anzeigen",
    'calloutA': u"Variante A",
    'calloutB': u"Variante B",
    'allowTurretRotation': u"Turmdrehung mit der Maus erlauben",
    'layoutDebug': u"Debuganzeige der Platzierungszonen",
    'rear': u"Hinterer Sichtbarkeitspunkt",
    'front': u"Vorderer Sichtbarkeitspunkt",
    'left': u"Linker seitlicher Sichtbarkeitspunkt",
    'right': u"Rechter seitlicher Sichtbarkeitspunkt",
    'gunStatic': u"Fester Sichtbarkeitspunkt am Geschütz",
    'top': u"Oberer Sichtbarkeitspunkt / Sichtfenster",
    'gunMoving': u"Sichtbarkeitspunkt am Geschütz / Sichtfenster",
  },
  'el': {
    'modName': u"Σημεία ελέγχου ορατότητας",
    'modDescription': u"Ρυθμίσεις σημείων ελέγχου ορατότητας και παρατήρησης",
    'title': u"Σημεία ελέγχου ορατότητας και παρατήρησης",
    'showMaskPoints': u"Σημεία ελέγχου ορατότητας",
    'showSpotPoints': u"Σημεία παρατήρησης",
    'showUiPoints': u"Εμφάνιση δεικτών",
    'showGuides': u"Γραμμές οδήγησης",
    'showTooltips': u"Εμφάνιση συμβουλών",
    'group3d': u"3D",
    'groupUi': u"UI",
    'callouts': u"Ετικέτες",
    'calloutOff': u"Να μην εμφανίζονται",
    'calloutA': u"Παραλλαγή A",
    'calloutB': u"Παραλλαγή B",
    'allowTurretRotation': u"Να επιτρέπεται η περιστροφή πύργου με το ποντίκι",
    'layoutDebug': u"Εμφάνιση αποσφαλμάτωσης ζωνών τοποθέτησης",
    'rear': u"Πίσω σημείο ελέγχου ορατότητας",
    'front': u"Μπροστινό σημείο ελέγχου ορατότητας",
    'left': u"Αριστερό πλευρικό σημείο ελέγχου ορατότητας",
    'right': u"Δεξί πλευρικό σημείο ελέγχου ορατότητας",
    'gunStatic': u"Σταθερό σημείο ελέγχου ορατότητας πυροβόλου",
    'top': u"Επάνω σημείο ελέγχου ορατότητας / σημείο παρατήρησης",
    'gunMoving': u"Σημείο ελέγχου ορατότητας πυροβόλου / σημείο παρατήρησης",
  },
  'en': {
    'modName': u"Visibility checkpoints",
    'modDescription': u"Configure visibility checkpoints and view range ports",
    'title': u"Visibility checkpoints and view range ports",
    'showMaskPoints': u"Visibility checkpoints",
    'showSpotPoints': u"View range ports",
    'showUiPoints': u"Show markers",
    'showGuides': u"Guides",
    'showTooltips': u"Show tooltips",
    'group3d': u"3D",
    'groupUi': u"UI",
    'callouts': u"Labels",
    'calloutOff': u"Do not show",
    'calloutA': u"Variant A",
    'calloutB': u"Variant B",
    'allowTurretRotation': u"Allow mouse turret rotation",
    'layoutDebug': u"Debug drawing of placement zones",
    'rear': u"Rear visibility checkpoint",
    'front': u"Front visibility checkpoint",
    'left': u"Left-side visibility checkpoint",
    'right': u"Right-side visibility checkpoint",
    'gunStatic': u"Initial gun visibility checkpoint",
    'top': u"Upper visibility checkpoint / view range port",
    'gunMoving': u"Gun visibility checkpoint / view range port",
  },
  'es': {
    'modName': u"Puntos de control de visibilidad",
    'modDescription': u"Ajustes de los puntos de control de visibilidad y puertos de alcance de visión",
    'title': u"Puntos de control de visibilidad y puertos de alcance de visión",
    'showMaskPoints': u"Puntos de control de visibilidad",
    'showSpotPoints': u"Puertos de alcance de visión",
    'showUiPoints': u"Mostrar marcadores",
    'showGuides': u"Guías",
    'showTooltips': u"Mostrar ayudas",
    'group3d': u"3D",
    'groupUi': u"IU",
    'callouts': u"Etiquetas",
    'calloutOff': u"No mostrar",
    'calloutA': u"Variante A",
    'calloutB': u"Variante B",
    'allowTurretRotation': u"Permitir girar la torreta con el ratón",
    'layoutDebug': u"Dibujo de depuración de zonas de colocación",
    'rear': u"Punto de control de visibilidad trasero",
    'front': u"Punto de control de visibilidad delantero",
    'left': u"Punto de control de visibilidad lateral izquierdo",
    'right': u"Punto de control de visibilidad lateral derecho",
    'gunStatic': u"Punto de control de visibilidad inicial del cañón",
    'top': u"Punto de control de visibilidad superior / puerto de alcance de visión",
    'gunMoving': u"Punto de control de visibilidad del cañón / puerto de alcance de visión",
  },
  'fi': {
    'modName': u"Näkyvyyden tarkistuspisteet",
    'modDescription': u"Näkyvyyden tarkistus- ja tähystyspisteiden asetukset",
    'title': u"Näkyvyyden tarkistus- ja tähystyspisteet",
    'showMaskPoints': u"Näkyvyyden tarkistuspisteet",
    'showSpotPoints': u"Tähystyspisteet",
    'showUiPoints': u"Näytä merkit",
    'showGuides': u"Apulinjat",
    'showTooltips': u"Näytä työkaluvihjeet",
    'group3d': u"3D",
    'groupUi': u"UI",
    'callouts': u"Nimilaput",
    'calloutOff': u"Älä näytä",
    'calloutA': u"Vaihtoehto A",
    'calloutB': u"Vaihtoehto B",
    'allowTurretRotation': u"Salli tornin kääntäminen hiirellä",
    'layoutDebug': u"Sijoitusalueiden virheenkorjauspiirto",
    'rear': u"Takimmainen näkyvyyden tarkistuspiste",
    'front': u"Etummainen näkyvyyden tarkistuspiste",
    'left': u"Vasen näkyvyyden tarkistuspiste",
    'right': u"Oikea näkyvyyden tarkistuspiste",
    'gunStatic': u"Tykin kiinteä näkyvyyden tarkistuspiste",
    'top': u"Ylempi näkyvyyden tarkistuspiste / tähystyspiste",
    'gunMoving': u"Tykin näkyvyyden tarkistuspiste / tähystyspiste",
  },
  'fr': {
    'modName': u"Points de visibilité",
    'modDescription': u"Réglages des points de visibilité et des ports de portée de vue",
    'title': u"Points de visibilité et ports de portée de vue",
    'showMaskPoints': u"Points de visibilité",
    'showSpotPoints': u"Ports de portée de vue",
    'showUiPoints': u"Afficher les marqueurs",
    'showGuides': u"Repères",
    'showTooltips': u"Afficher les infobulles",
    'group3d': u"3D",
    'groupUi': u"UI",
    'callouts': u"Étiquettes",
    'calloutOff': u"Ne pas afficher",
    'calloutA': u"Variante A",
    'calloutB': u"Variante B",
    'allowTurretRotation': u"Autoriser la rotation de la tourelle à la souris",
    'layoutDebug': u"Affichage de débogage des zones de placement",
    'rear': u"Point de visibilité arrière",
    'front': u"Point de visibilité avant",
    'left': u"Point de visibilité latéral gauche",
    'right': u"Point de visibilité latéral droit",
    'gunStatic': u"Point de visibilité initial du canon",
    'top': u"Point de visibilité supérieur / port de portée de vue",
    'gunMoving': u"Point de visibilité du canon / port de portée de vue",
  },
  'hr': {
    'modName': u"Točke vidljivosti",
    'modDescription': u"Postavke točaka vidljivosti i osmatračkih točaka",
    'title': u"Točke vidljivosti i osmatračke točke",
    'showMaskPoints': u"Točke vidljivosti",
    'showSpotPoints': u"Osmatračke točke",
    'showUiPoints': u"Prikaži oznake",
    'showGuides': u"Vodilice",
    'showTooltips': u"Prikaži savjete",
    'group3d': u"3D",
    'groupUi': u"UI",
    'callouts': u"Natpisi",
    'calloutOff': u"Ne prikazuj",
    'calloutA': u"Varijanta A",
    'calloutB': u"Varijanta B",
    'allowTurretRotation': u"Dopusti okretanje kupole mišem",
    'layoutDebug': u"Prikaz zona postavljanja za otklanjanje pogrešaka",
    'rear': u"Stražnja točka vidljivosti",
    'front': u"Prednja točka vidljivosti",
    'left': u"Lijeva bočna točka vidljivosti",
    'right': u"Desna bočna točka vidljivosti",
    'gunStatic': u"Početna točka vidljivosti topa",
    'top': u"Gornja točka vidljivosti / osmatračka točka",
    'gunMoving': u"Točka vidljivosti topa / osmatračka točka",
  },
  'hu': {
    'modName': u"Láthatósági ellenőrzőpontok",
    'modDescription': u"A láthatósági ellenőrzőpontok és látótávolsági portok beállításai",
    'title': u"Láthatósági ellenőrzőpontok és látótávolsági portok",
    'showMaskPoints': u"Láthatósági ellenőrzőpontok",
    'showSpotPoints': u"Látótávolsági portok",
    'showUiPoints': u"Jelölők megjelenítése",
    'showGuides': u"Segédvonalak",
    'showTooltips': u"Eszköztippek megjelenítése",
    'group3d': u"3D",
    'groupUi': u"UI",
    'callouts': u"Címkék",
    'calloutOff': u"Ne jelenjen meg",
    'calloutA': u"A változat",
    'calloutB': u"B változat",
    'allowTurretRotation': u"Torony forgatása egérrel",
    'layoutDebug': u"Elhelyezési zónák hibakeresési rajza",
    'rear': u"Hátsó láthatósági ellenőrzőpont",
    'front': u"Első láthatósági ellenőrzőpont",
    'left': u"Bal oldali láthatósági ellenőrzőpont",
    'right': u"Jobb oldali láthatósági ellenőrzőpont",
    'gunStatic': u"Löveg kezdeti láthatósági ellenőrzőpontja",
    'top': u"Felső láthatósági ellenőrzőpont / látótávolsági port",
    'gunMoving': u"Löveg láthatósági ellenőrzőpontja / látótávolsági portja",
  },
  'it': {
    'modName': u"Punti di controllo di visibilità",
    'modDescription': u"Impostazioni dei punti di controllo di visibilità e delle feritoie del raggio visivo",
    'title': u"Punti di controllo di visibilità e feritoie del raggio visivo",
    'showMaskPoints': u"Punti di controllo di visibilità",
    'showSpotPoints': u"Feritoie del raggio visivo",
    'showUiPoints': u"Mostra indicatori",
    'showGuides': u"Linee guida",
    'showTooltips': u"Mostra suggerimenti",
    'group3d': u"3D",
    'groupUi': u"UI",
    'callouts': u"Etichette",
    'calloutOff': u"Non mostrare",
    'calloutA': u"Variante A",
    'calloutB': u"Variante B",
    'allowTurretRotation': u"Consenti la rotazione della torretta con il mouse",
    'layoutDebug': u"Disegno di debug delle zone di posizionamento",
    'rear': u"Punto di controllo di visibilità posteriore",
    'front': u"Punto di controllo di visibilità anteriore",
    'left': u"Punto di controllo di visibilità laterale sinistro",
    'right': u"Punto di controllo di visibilità laterale destro",
    'gunStatic': u"Punto di controllo di visibilità iniziale del cannone",
    'top': u"Punto di controllo di visibilità superiore / feritoia del raggio visivo",
    'gunMoving': u"Punto di controllo di visibilità del cannone / feritoia del raggio visivo",
  },
  'lt': {
    'modName': u"Matomumo kontrolės taškai",
    'modDescription': u"Matomumo kontrolės ir stebėjimo taškų nustatymai",
    'title': u"Matomumo kontrolės ir stebėjimo taškai",
    'showMaskPoints': u"Matomumo kontrolės taškai",
    'showSpotPoints': u"Stebėjimo taškai",
    'showUiPoints': u"Rodyti žymeklius",
    'showGuides': u"Kreipiamosios",
    'showTooltips': u"Rodyti paaiškinimus",
    'group3d': u"3D",
    'groupUi': u"UI",
    'callouts': u"Etiketės",
    'calloutOff': u"Nerodyti",
    'calloutA': u"A variantas",
    'calloutB': u"B variantas",
    'allowTurretRotation': u"Leisti sukti bokštelį pele",
    'layoutDebug': u"Išdėstymo zonų derinimo vaizdas",
    'rear': u"Galinis matomumo kontrolės taškas",
    'front': u"Priekinis matomumo kontrolės taškas",
    'left': u"Kairysis šoninis matomumo kontrolės taškas",
    'right': u"Dešinysis šoninis matomumo kontrolės taškas",
    'gunStatic': u"Pradinis pabūklo matomumo kontrolės taškas",
    'top': u"Viršutinis matomumo kontrolės taškas / stebėjimo taškas",
    'gunMoving': u"Pabūklo matomumo kontrolės taškas / stebėjimo taškas",
  },
  'lv': {
    'modName': u"Redzamības kontrolpunkti",
    'modDescription': u"Redzamības kontrolpunktu un novērošanas punktu iestatījumi",
    'title': u"Redzamības kontrolpunkti un novērošanas punkti",
    'showMaskPoints': u"Redzamības kontrolpunkti",
    'showSpotPoints': u"Novērošanas punkti",
    'showUiPoints': u"Rādīt marķierus",
    'showGuides': u"Palīglīnijas",
    'showTooltips': u"Rādīt rīka padomus",
    'group3d': u"3D",
    'groupUi': u"UI",
    'callouts': u"Iezīmes",
    'calloutOff': u"Nerādīt",
    'calloutA': u"A variants",
    'calloutB': u"B variants",
    'allowTurretRotation': u"Atļaut torņa pagriešanu ar peli",
    'layoutDebug': u"Izvietojuma zonu atkļūdošanas zīmējums",
    'rear': u"Aizmugurējais redzamības kontrolpunkts",
    'front': u"Priekšējais redzamības kontrolpunkts",
    'left': u"Kreisais sānu redzamības kontrolpunkts",
    'right': u"Labais sānu redzamības kontrolpunkts",
    'gunStatic': u"Sākotnējais lielgabala redzamības kontrolpunkts",
    'top': u"Augšējais redzamības kontrolpunkts / novērošanas punkts",
    'gunMoving': u"Lielgabala redzamības kontrolpunkts / novērošanas punkts",
  },
  'nl': {
    'modName': u"Zichtbaarheidscontrolepunten",
    'modDescription': u"Instellingen voor zichtbaarheidscontrole- en waarnemingspunten",
    'title': u"Zichtbaarheidscontrole- en waarnemingspunten",
    'showMaskPoints': u"Zichtbaarheidscontrolepunten",
    'showSpotPoints': u"Waarnemingspunten",
    'showUiPoints': u"Markeringen tonen",
    'showGuides': u"Hulplijnen",
    'showTooltips': u"Tooltips tonen",
    'group3d': u"3D",
    'groupUi': u"UI",
    'callouts': u"Labels",
    'calloutOff': u"Niet tonen",
    'calloutA': u"Variant A",
    'calloutB': u"Variant B",
    'allowTurretRotation': u"Torenrotatie met de muis toestaan",
    'layoutDebug': u"Debugweergave van plaatsingszones",
    'rear': u"Achterste zichtbaarheidscontrolepunt",
    'front': u"Voorste zichtbaarheidscontrolepunt",
    'left': u"Linker zichtbaarheidscontrolepunt",
    'right': u"Rechter zichtbaarheidscontrolepunt",
    'gunStatic': u"Vast zichtbaarheidscontrolepunt van het kanon",
    'top': u"Bovenste zichtbaarheidscontrolepunt / waarnemingspunt",
    'gunMoving': u"Zichtbaarheidscontrolepunt van het kanon / waarnemingspunt",
  },
  'no': {
    'modName': u"Synlighetskontrollpunkter",
    'modDescription': u"Innstillinger for synlighetskontroll- og observasjonspunkter",
    'title': u"Synlighetskontroll- og observasjonspunkter",
    'showMaskPoints': u"Synlighetskontrollpunkter",
    'showSpotPoints': u"Observasjonspunkter",
    'showUiPoints': u"Vis markører",
    'showGuides': u"Hjelpelinjer",
    'showTooltips': u"Vis verktøytips",
    'group3d': u"3D",
    'groupUi': u"UI",
    'callouts': u"Etiketter",
    'calloutOff': u"Ikke vis",
    'calloutA': u"Variant A",
    'calloutB': u"Variant B",
    'allowTurretRotation': u"Tillat tårnrotasjon med musen",
    'layoutDebug': u"Feilsøkingsvisning av plasseringssoner",
    'rear': u"Bakre synlighetskontrollpunkt",
    'front': u"Fremre synlighetskontrollpunkt",
    'left': u"Venstre synlighetskontrollpunkt",
    'right': u"Høyre synlighetskontrollpunkt",
    'gunStatic': u"Fast synlighetskontrollpunkt ved kanonen",
    'top': u"Øvre synlighetskontrollpunkt / observasjonspunkt",
    'gunMoving': u"Kanonens synlighetskontrollpunkt / observasjonspunkt",
  },
  'pl': {
    'modName': u"Punkty kontrolne widoczności",
    'modDescription': u"Ustawienia punktów kontrolnych widoczności i portów zasięgu widzenia",
    'title': u"Punkty kontrolne widoczności i porty zasięgu widzenia",
    'showMaskPoints': u"Punkty kontrolne widoczności",
    'showSpotPoints': u"Porty zasięgu widzenia",
    'showUiPoints': u"Pokaż znaczniki",
    'showGuides': u"Linie pomocnicze",
    'showTooltips': u"Pokaż podpowiedzi",
    'group3d': u"3D",
    'groupUi': u"UI",
    'callouts': u"Etykiety",
    'calloutOff': u"Nie pokazuj",
    'calloutA': u"Wariant A",
    'calloutB': u"Wariant B",
    'allowTurretRotation': u"Zezwól na obrót wieży myszą",
    'layoutDebug': u"Widok debugowania stref rozmieszczenia",
    'rear': u"Tylny punkt kontrolny widoczności",
    'front': u"Przedni punkt kontrolny widoczności",
    'left': u"Lewy boczny punkt kontrolny widoczności",
    'right': u"Prawy boczny punkt kontrolny widoczności",
    'gunStatic': u"Początkowy punkt kontrolny widoczności działa",
    'top': u"Górny punkt kontrolny widoczności / port zasięgu widzenia",
    'gunMoving': u"Punkt kontrolny widoczności działa / port zasięgu widzenia",
  },
  'pt': {
    'modName': u"Pontos de detecção",
    'modDescription': u"Definições dos pontos de detecção e portas de visão",
    'title': u"Pontos de detecção e portas de visão",
    'showMaskPoints': u"Pontos de detecção",
    'showSpotPoints': u"Portas de visão",
    'showUiPoints': u"Mostrar marcadores",
    'showGuides': u"Guias",
    'showTooltips': u"Mostrar dicas",
    'group3d': u"3D",
    'groupUi': u"IU",
    'callouts': u"Rótulos",
    'calloutOff': u"Não mostrar",
    'calloutA': u"Variante A",
    'calloutB': u"Variante B",
    'allowTurretRotation': u"Permitir girar a torre com o rato",
    'layoutDebug': u"Desenho de depuração das zonas de posicionamento",
    'rear': u"Ponto de detecção traseiro",
    'front': u"Ponto de detecção dianteiro",
    'left': u"Ponto de detecção lateral esquerdo",
    'right': u"Ponto de detecção lateral direito",
    'gunStatic': u"Ponto de detecção inicial do canhão",
    'top': u"Ponto de detecção superior / porta de visão",
    'gunMoving': u"Ponto de detecção do canhão / porta de visão",
  },
  'ro': {
    'modName': u"Puncte de control al vizibilității",
    'modDescription': u"Setări pentru punctele de control al vizibilității și punctele de vizualizare",
    'title': u"Puncte de control al vizibilității și puncte de vizualizare",
    'showMaskPoints': u"Puncte de control al vizibilității",
    'showSpotPoints': u"Puncte de vizualizare",
    'showUiPoints': u"Afișează marcajele",
    'showGuides': u"Ghidaje",
    'showTooltips': u"Afișează indicii",
    'group3d': u"3D",
    'groupUi': u"IU",
    'callouts': u"Etichete",
    'calloutOff': u"Nu afișa",
    'calloutA': u"Varianta A",
    'calloutB': u"Varianta B",
    'allowTurretRotation': u"Permite rotirea turelei cu mouse-ul",
    'layoutDebug': u"Afișare de depanare a zonelor de plasare",
    'rear': u"Punct de control posterior al vizibilității",
    'front': u"Punct de control frontal al vizibilității",
    'left': u"Punct de control lateral stânga al vizibilității",
    'right': u"Punct de control lateral dreapta al vizibilității",
    'gunStatic': u"Punct de control inițial al vizibilității tunului",
    'top': u"Punct de control superior al vizibilității / punct de vizualizare",
    'gunMoving': u"Punct de control al vizibilității tunului / punct de vizualizare",
  },
  'ru': {
    'modName': u"Габаритные точки",
    'modDescription': u"Настройки габаритных и обзорных точек",
    'title': u"Габаритные и обзорные точки",
    'showMaskPoints': u"Габаритные точки",
    'showSpotPoints': u"Обзорные точки",
    'showUiPoints': u"Отображать маркеры",
    'showGuides': u"Направляющие",
    'showTooltips': u"Отображать подсказки",
    'group3d': u"3D",
    'groupUi': u"UI",
    'callouts': u"Сноски",
    'calloutOff': u"Не отображать",
    'calloutA': u"Вариант А",
    'calloutB': u"Вариант Б",
    'allowTurretRotation': u"Разрешить вращение башни мышью",
    'layoutDebug': u"Отладочная отрисовка зон размещения",
    'rear': u"Задняя габаритная",
    'front': u"Передняя габаритная",
    'left': u"Левая бортовая габаритная",
    'right': u"Правая бортовая габаритная",
    'gunStatic': u"Исходная орудийная габаритная",
    'top': u"Верхняя обзорно-габаритная",
    'gunMoving': u"Орудийная обзорно-габаритная",
  },
  'sr': {
    'modName': u"Tačke vidljivosti",
    'modDescription': u"Podešavanja tačaka vidljivosti i osmatračkih tačaka",
    'title': u"Tačke vidljivosti i osmatračke tačke",
    'showMaskPoints': u"Tačke vidljivosti",
    'showSpotPoints': u"Osmatračke tačke",
    'showUiPoints': u"Prikaži oznake",
    'showGuides': u"Vođice",
    'showTooltips': u"Prikaži savete",
    'group3d': u"3D",
    'groupUi': u"UI",
    'callouts': u"Natpisi",
    'calloutOff': u"Ne prikazuj",
    'calloutA': u"Varijanta A",
    'calloutB': u"Varijanta B",
    'allowTurretRotation': u"Dozvoli okretanje kupole mišem",
    'layoutDebug': u"Prikaz zona postavljanja za otklanjanje grešaka",
    'rear': u"Zadnja tačka vidljivosti",
    'front': u"Prednja tačka vidljivosti",
    'left': u"Leva bočna tačka vidljivosti",
    'right': u"Desna bočna tačka vidljivosti",
    'gunStatic': u"Početna tačka vidljivosti topa",
    'top': u"Gornja tačka vidljivosti / osmatračka tačka",
    'gunMoving': u"Tačka vidljivosti topa / osmatračka tačka",
  },
  'sv': {
    'modName': u"Synlighetskontrollpunkter",
    'modDescription': u"Inställningar för synlighetskontroll- och observationspunkter",
    'title': u"Synlighetskontroll- och observationspunkter",
    'showMaskPoints': u"Synlighetskontrollpunkter",
    'showSpotPoints': u"Observationspunkter",
    'showUiPoints': u"Visa markörer",
    'showGuides': u"Hjälplinjer",
    'showTooltips': u"Visa verktygstips",
    'group3d': u"3D",
    'groupUi': u"UI",
    'callouts': u"Etiketter",
    'calloutOff': u"Visa inte",
    'calloutA': u"Variant A",
    'calloutB': u"Variant B",
    'allowTurretRotation': u"Tillåt tornrotation med musen",
    'layoutDebug': u"Felsökningsvisning av placeringszoner",
    'rear': u"Bakre synlighetskontrollpunkt",
    'front': u"Främre synlighetskontrollpunkt",
    'left': u"Vänster synlighetskontrollpunkt",
    'right': u"Höger synlighetskontrollpunkt",
    'gunStatic': u"Fast synlighetskontrollpunkt vid kanonen",
    'top': u"Övre synlighetskontrollpunkt / observationspunkt",
    'gunMoving': u"Kanonens synlighetskontrollpunkt / observationspunkt",
  },
  'tr': {
    'modName': u"Görüş kontrol noktaları",
    'modDescription': u"Görüş kontrol noktaları ve görüş menzili yuvaları ayarları",
    'title': u"Görüş kontrol noktaları ve görüş menzili yuvaları",
    'showMaskPoints': u"Görüş kontrol noktaları",
    'showSpotPoints': u"Görüş menzili yuvaları",
    'showUiPoints': u"İşaretçileri göster",
    'showGuides': u"Kılavuzlar",
    'showTooltips': u"İpuçlarını göster",
    'group3d': u"3D",
    'groupUi': u"UI",
    'callouts': u"Etiketler",
    'calloutOff': u"Gösterme",
    'calloutA': u"A seçeneği",
    'calloutB': u"B seçeneği",
    'allowTurretRotation': u"Fareyle kule döndürmeye izin ver",
    'layoutDebug': u"Yerleşim bölgelerinin hata ayıklama çizimi",
    'rear': u"Arka görüş kontrol noktası",
    'front': u"Ön görüş kontrol noktası",
    'left': u"Sol yan görüş kontrol noktası",
    'right': u"Sağ yan görüş kontrol noktası",
    'gunStatic': u"Topun başlangıç görüş kontrol noktası",
    'top': u"Üst görüş kontrol noktası / görüş menzili yuvası",
    'gunMoving': u"Topun görüş kontrol noktası / görüş menzili yuvası",
  },
  'uk': {
    'modName': u"Габаритні точки",
    'modDescription': u"Налаштування габаритних і оглядових точок",
    'title': u"Габаритні та оглядові точки",
    'showMaskPoints': u"Габаритні точки",
    'showSpotPoints': u"Оглядові точки",
    'showUiPoints': u"Показувати маркери",
    'showGuides': u"Напрямні",
    'showTooltips': u"Показувати підказки",
    'group3d': u"3D",
    'groupUi': u"UI",
    'callouts': u"Підписи",
    'calloutOff': u"Не показувати",
    'calloutA': u"Варіант А",
    'calloutB': u"Варіант Б",
    'allowTurretRotation': u"Дозволити обертання башти мишею",
    'layoutDebug': u"Налагоджувальне малювання зон розміщення",
    'rear': u"Задня габаритна",
    'front': u"Передня габаритна",
    'left': u"Ліва бортова габаритна",
    'right': u"Права бортова габаритна",
    'gunStatic': u"Початкова гарматна габаритна",
    'top': u"Верхня оглядово-габаритна",
    'gunMoving': u"Гарматна оглядово-габаритна",
  },
}

# Tooltip copy is kept in paragraphs rather than in the compact UI-label table.
# Languages without reviewed long-form copy use English descriptions while
# retaining their translated point names in the heading.
_TOOLTIP_BODIES = {
  'ru': {
    'rear': u'Центр задней грани габаритов корпуса: посередине её ширины и высоты.',
    'front': u'Центр передней грани габаритов корпуса: посередине её ширины и высоты.',
    'left': u'Точка на левой грани габаритов корпуса, посередине её длины, поднятая на высоту крепления орудия.',
    'right': u'Точка на правой грани габаритов корпуса, посередине её длины, поднятая на высоту крепления орудия.',
    'gunStatic': (
      u'Положение крепления орудия (ось, вокруг которой орудие '
      u'поднимается и опускается) при нулевом повороте башни. '
      u'При вращении башни точка остаётся на месте.'),
    'top': (
      u'Над началом координат машины, на высоте верхней границы '
      u'корпуса или башни — в зависимости от того, что выше. Эта '
      u'точка не обязательно совпадает с центром верхней грани, '
      u'хотя часто находится близко к нему.'),
    'gunMoving': (
      u'Текущее положение крепления орудия (ось, вокруг которой '
      u'орудие поднимается и опускается). Точка следует за '
      u'поворотом башни.'),
    'combinedGun': (
      u'В этом месте совпадают две точки в месте крепления орудия '
      u'к башне (ось, вокруг которой орудие поднимается и опускается).'
      u'\n\nИсходная орудийная габаритная — всегда остаётся на месте '
      u'нулевого поворота башни.'
      u'\n\nОрудийная обзорно-габаритная — следует за поворотом башни.'
      u'\n\nПри повороте башни точки разъединяются.'),
  },
  'en': {
    'rear': u'The center of the rear face of the hull bounds, halfway across its width and height.',
    'front': u'The center of the front face of the hull bounds, halfway across its width and height.',
    'left': u'A point on the left face of the hull bounds, halfway along its length, raised to the gun mount height.',
    'right': u'A point on the right face of the hull bounds, halfway along its length, raised to the gun mount height.',
    'gunStatic': (
      u'The gun mount position (the axis around which the gun elevates '
      u'and depresses) with the turret at zero rotation. This point '
      u'stays in place as the turret turns.'),
    'top': (
      u'Above the vehicle origin, at the upper bound of the hull or '
      u'turret, whichever is higher. This point does not necessarily '
      u'coincide with the center of the upper face, though it is often nearby.'),
    'gunMoving': (
      u'The current gun mount position (the axis around which the gun '
      u'elevates and depresses). This point follows the turret as it turns.'),
    'combinedGun': (
      u'Two points coincide here at the gun mount on the turret '
      u'(the axis around which the gun elevates and depresses).'
      u'\n\nThe initial gun visibility checkpoint stays at the '
      u'zero-rotation turret position.'
      u'\n\nThe gun visibility checkpoint / view range port '
      u'follows the turret as it turns.'
      u'\n\nThe points separate when the turret turns.'),
  },
}

_COMBINED_GUN_TITLES = {
  'ru': u'Исходная орудийная габаритная и орудийная обзорно-габаритная',
  'en': (u'Initial gun visibility checkpoint and gun visibility '
    u'checkpoint / view range port'),
}


def normalizeLanguage(language):
  if language is None:
    return DEFAULT_LANGUAGE

  try:
    language = language.decode('ascii')
  except AttributeError:
    pass
  except UnicodeDecodeError:
    return DEFAULT_LANGUAGE

  code = language.strip().lower().replace('-', '_')

  if code in _TRANSLATIONS:
    return code

  baseCode = code.split('_', 1)[0]

  return baseCode if baseCode in _TRANSLATIONS else DEFAULT_LANGUAGE


def getClientLanguageCode():
  try:
    from helpers import getClientLanguage
  except ImportError:
    return DEFAULT_LANGUAGE

  return normalizeLanguage(getClientLanguage())


def _getTranslation(language=None):
  code = (getClientLanguageCode() if language is None
      else normalizeLanguage(language))
  return _TRANSLATIONS[code]


def getModListLabels(language=None):
  translation = _getTranslation(language)
  return {
    'name': translation['modName'],
    'description': translation['modDescription'],
  }


def getSettingsLabels(language=None):
  translation = _getTranslation(language)
  keys = (
    'title', 'showMaskPoints', 'showSpotPoints', 'showUiPoints',
    'showGuides', 'showTooltips', 'group3d', 'groupUi', 'callouts',
    'allowTurretRotation', 'layoutDebug',
  )
  labels = dict((key, translation[key]) for key in keys)
  labels['calloutModes'] = [
    translation['calloutOff'],
    translation['calloutA'],
    translation['calloutB'],
  ]

  return labels


def getMarkerLabels(language=None):
  translation = _getTranslation(language)
  return dict((key, translation[key]) for key in (
    'rear', 'front', 'left', 'right', 'gunStatic', 'top', 'gunMoving'))


def getMarkerTooltips(language=None):
  code = (getClientLanguageCode() if language is None
      else normalizeLanguage(language))
  labels = getMarkerLabels(code)
  bodies = _TOOLTIP_BODIES.get(code, _TOOLTIP_BODIES['en'])
  result = dict((key, {'title': title, 'body': bodies[key]})
        for key, title in labels.items())
  result['combinedGun'] = {
    'title': _COMBINED_GUN_TITLES.get(
      code, u'%s / %s' % (labels['gunStatic'], labels['gunMoving'])),
    'body': bodies['combinedGun'],
  }

  return result
